<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\BranikBot.Infrastructure\BranikBot.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json" CopyToPublishDirectory="Always" CopyToOutputDirectory="Always"/>
        <None Update="appsettings.*.json" CopyToPublishDirectory="Never" CopyToOutputDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

</Project>
