name: branik-bot-development
services:
  branikbot:
    image: branikbot_development
    build:
      context: ./src
      dockerfile: BranikBot.ConsoleApp/Dockerfile
    container_name: branik_bot
    environment:
      - DOTNET_ENVIRONMENT=Development
