name: branik-bot-prod

services:
  branik-bot:
    build:
      context: ./src
      dockerfile: BranikBot.ConsoleApp/Dockerfile
    container_name: branik-bot
    environment:
      - DOTNET_ENVIRONMENT=Production
