services:
  branik-bot:
    image: mscepka/branik-bot:latest
    container_name: branik-bot
    environment:
      - DOTNET_ENVIRONMENT=Production
      - Discord__BotToken=${DISCORD_BOT_TOKEN}
    restart: unless-stopped
