name: branik-bot-dev

services:
  branik-bot:
    build:
      context: ./src
      dockerfile: BranikBot.ConsoleApp/Dockerfile
    container_name: branik-bot-local
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Discord__BotToken=<BOT_TOKEN>
