<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.1" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
      <PackageReference Include="NetCord.Hosting" Version="1.0.0-alpha.342" />
      <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-alpha.342" />
    </ItemGroup>

</Project>
