<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" />
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="NetCord.Hosting" />
        <PackageReference Include="NetCord.Hosting.Services" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Async" />
        <PackageReference Include="Serilog.Sinks.Console" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BranikBot.Application\BranikBot.Application.csproj"/>
    </ItemGroup>

</Project>
