<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BranikBot.Infrastructure\BranikBot.Infrastructure.csproj"/>
        <ProjectReference Include="..\BranikBot.Application\BranikBot.Application.csproj"/>
        <ProjectReference Include="..\BranikBot.Domain\BranikBot.Domain.csproj"/>
    </ItemGroup>

</Project>
