name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_project:
          - src/BranikBot.Tests/BranikBot.Tests.csproj

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Restore dependencies (${{ matrix.test_project }})
      run: dotnet restore ${{ matrix.test_project }}
      
    - name: Run tests (${{ matrix.test_project }})
      run: dotnet test ${{ matrix.test_project }} --verbosity normal --logger "trx" --results-directory ./TestResults
